"""change name of table Taskskills to TaskSkills

Revision ID: 29cdd435396b
Revises: 6712828a5cea
Create Date: 2021-08-19 14:25:24.623767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cdd435396b'
down_revision = '6712828a5cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('taskskills','task_skills')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskskills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name='task_skills_skill_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='task_skills_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_skills_pkey')
    )
    op.drop_table('task_skills')
    # ### end Alembic commands ###
