"""change classname task_skills to Taskskills

Revision ID: 4fc365422ef2
Revises: 3bb8c777a7d0
Create Date: 2021-08-18 16:57:50.090375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc365422ef2'
down_revision = '3bb8c777a7d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taskskills', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskskills', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
