"""Add Association table TaskSkills

Revision ID: d512d1b9055d
Revises: 2b627fb26112
Create Date: 2021-08-14 09:57:37.262864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd512d1b9055d'
down_revision = '2b627fb26112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('skill_task_id_fkey', 'skill', type_='foreignkey')
    op.drop_column('skill', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('skill_task_id_fkey', 'skill', 'task', ['task_id'], ['id'])
    op.drop_table('task_skills')
    # ### end Alembic commands ###
