"""alter status to skill_status

Revision ID: 0c86d858cabb
Revises: 29cdd435396b
Create Date: 2021-08-19 19:30:09.180446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c86d858cabb'
down_revision = '29cdd435396b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('task_skills', sa.Column('skill_status', sa.String(length=50), nullable=True))
    op.alter_column('task_skills', 'status', nullable=True, new_column_name='skill_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_skills', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('task_skills', 'skill_status')
    # ### end Alembic commands ###
