"""add field status

Revision ID: 3bb8c777a7d0
Revises: d512d1b9055d
Create Date: 2021-08-18 16:08:18.540388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb8c777a7d0'
down_revision = 'd512d1b9055d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_skills', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_skills', 'status')
    # ### end Alembic commands ###
