"""add status field in claass Taskskills

Revision ID: 6712828a5cea
Revises: 4fc365422ef2
Create Date: 2021-08-18 16:59:16.318344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6712828a5cea'
down_revision = '4fc365422ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskskills', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taskskills', 'status')
    # ### end Alembic commands ###
